name: deploy

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: pm2 restart spotibot
